fix: Missing error message when edit note is invalid
> Uncaught TypeError: MBJS.texts is not a function

Spotted by @Quppa https://community.metabrainz.org/t/mass-merge-recordings-merge-duplicate-recordings-from-two-similar-releases/203168/158?u=jesus2099
Co-authored-by: jesus2099 <jesus2099@users.noreply.github.com>
Signed-off-by: jesus2099 <jesus2099@users.noreply.github.com>